#!/usr/bin/env python

import sys
import psutil

metric_to_print = sys.argv[1]

if sys.argv[1] == "cpu":
#print "input argumet 1 = ", metric_to_print
	cpu_output = psutil.cpu_times(percpu=False)
	print "system.cpu.idle", output[3]
	print "system.cpu.user", output[0]
	print "system.cpu.guest", output[8]
	print "system.cpu.iowait", output[4]
	print "system.cpu.stolen", output[7]
	print "system.cpu.system", output[2]
	print "ALL OUTPUT = \n", output
elif sys.argv[1] == "mem":
	mem_virt_output = psutil.virtual_memory()
	mem_swap_output = psutil.swap_memory()
	print "virtual total", mem_virt_output[0]
	print "virtual used", mem_virt_output[3]
	print "virtual free", mem_virt_output[4]
	print "virtual shared", mem_virt_output[9]
	# print "\n VIRUAL ALL OUTPUT = \n", mem_virt_output
	print "swap total", mem_swap_output[0]
	print "swap used", mem_swap_output[1]
	print "swap free", mem_swap_output[2]
	# print "\n SWAP ALL OUTPUT = \n", mem_swap_output

#	for metric in output:
#         print metric